[workspace]
resolver = "2"
members = [
    "collector",
    "mperf",
    "mperf-data",
    "mperf-gui",
    "pmu",
    "pmu-data",
    "shmem",
    "symbolize",
    "truth",
    "utils/event-import",
    "utils/qemu-roofline",
]

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3
mperf.opt-level = 3
