mod bottom_panel;
mod callers;
mod chrome;
mod cpu_heatmap;
pub(crate) mod flame_canvas;
mod flamegraph;
mod flamescope;
mod icicle;
mod memory;
mod metrics_timeline;
mod resources;
mod roofline;
mod sidebar;
mod source;
mod stack_timeline;
