name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    with:
      release_tag: ${{ github.event.release.tag_name }}
